In [1]:
import numpy as np

**Создание**

In [4]:
a = np.array([1, 2, 3])
print(a)
print(a.dtype)
print(a.ndim)
print(a.size)
print(len(a))

[1 2 3]
int32
1
3
3


In [5]:
a = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
print(a)
print(a.dtype)
print(a.ndim)
print(a.size)
print(len(a))

[[1. 2. 3.]
 [4. 5. 6.]]
float64
2
6
2


In [7]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
a = np.ones((3, 4, 5), dtype=np.int16)
a

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [29]:
a = np.full((3, 4), 'b')
print(a)
print(a.dtype)
print(a.dtype.name)

[['b' 'b' 'b' 'b']
 ['b' 'b' 'b' 'b']
 ['b' 'b' 'b' 'b']]
<U1
str32


In [11]:
a = np.random.random((4,))
a

array([0.94805663, 0.39572466, 0.49639618, 0.19276695])

In [12]:
a = np.random.random((4,)) * 5 + 6
a

array([ 7.04819022,  8.79757141, 10.64984589, 10.79433911])

In [13]:
a = np.random.randint(3, 5, size=(10,))
a

array([4, 4, 4, 3, 4, 3, 4, 4, 3, 3])

In [15]:
a = np.random.randint(5, size=(10,))  # с нуля
a

array([0, 1, 2, 2, 4, 1, 2, 0, 1, 4])

In [17]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
a = np.arange(1, 10, 2)
a

array([1, 3, 5, 7, 9])

In [21]:
a = np.arange(1, 10, 1.5)
a

array([1. , 2.5, 4. , 5.5, 7. , 8.5])

In [22]:
a = np.linspace(1, 9, 10)
a

array([1.        , 1.88888889, 2.77777778, 3.66666667, 4.55555556,
       5.44444444, 6.33333333, 7.22222222, 8.11111111, 9.        ])

In [24]:
a = np.empty((3, 2))  # not so empty!
a

array([[1. , 2.5],
       [4. , 5.5],
       [7. , 8.5]])

**Сохранить, загрузить**

In [25]:
np.save('my_array', a)

In [27]:
np.load('my_array.npy')

array([[1. , 2.5],
       [4. , 5.5],
       [7. , 8.5]])

**Преобразования**

In [30]:
a = np.linspace(1, 7, 4)
a

array([1., 3., 5., 7.])

In [31]:
b = a.astype(int)
b

array([1, 3, 5, 7])

In [32]:
b[1] = 0
b

array([1, 0, 5, 7])

In [33]:
a

array([1., 3., 5., 7.])

In [34]:
a = np.arange(4).reshape((2, 2))
a

array([[0, 1],
       [2, 3]])

In [39]:
b = np.linspace(0, 10, 4).reshape((2, -1))  # само подстроится
b

array([[ 0.        ,  3.33333333],
       [ 6.66666667, 10.        ]])

In [40]:
a * b

array([[ 0.        ,  3.33333333],
       [13.33333333, 30.        ]])

In [41]:
np.dot(a, b)

array([[ 6.66666667, 10.        ],
       [20.        , 36.66666667]])

In [42]:
a.dot(b)

array([[ 6.66666667, 10.        ],
       [20.        , 36.66666667]])

In [45]:
# Есть всевозможные функции
a[0, 0] = 3
print(np.log(a))
print(np.sin(a))
print(np.sqrt(a))

[[1.09861229 0.        ]
 [0.69314718 1.09861229]]
[[0.14112001 0.84147098]
 [0.90929743 0.14112001]]
[[1.73205081 1.        ]
 [1.41421356 1.73205081]]


In [46]:
a == b

array([[False, False],
       [False, False]])

In [47]:
b[0, 0] = 3
a == b

array([[ True, False],
       [False, False]])

In [48]:
np.array_equal(a, b)

False

**Средние и т.п.**

In [49]:
a

array([[3, 1],
       [2, 3]])

In [52]:
a.mean(), a.sum(), np.median(a)

(2.25, 9, 2.5)

In [53]:
a.cumsum(axis=0)

array([[3, 1],
       [5, 4]], dtype=int32)

In [55]:
a.cumsum(axis=1)

array([[3, 4],
       [2, 5]], dtype=int32)

In [58]:
a.std() # np.std(a)

0.82915619758885

**Копирование, глубокое и не очень**

In [71]:
a = np.arange(4).reshape((2, 2))

In [72]:
b = a.view()
b

array([[0, 1],
       [2, 3]])

In [73]:
c = a.copy()
c

array([[0, 1],
       [2, 3]])

In [74]:
d = np.copy(a)
d

array([[0, 1],
       [2, 3]])

In [75]:
d[0, 0] = 5
a

array([[0, 1],
       [2, 3]])

In [76]:
c[0, 0] = 6
a

array([[0, 1],
       [2, 3]])

In [77]:
b[0, 0] = 7  # Хоба!
a

array([[7, 1],
       [2, 3]])

In [78]:
c

array([[6, 1],
       [2, 3]])

In [79]:
d

array([[5, 1],
       [2, 3]])

In [80]:
a.sort()
a

array([[1, 7],
       [2, 3]])

In [82]:
a.sort(axis=0)
a

array([[1, 3],
       [2, 7]])

**Слайсинг**

In [83]:
a = np.arange(20).reshape((4, 5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [86]:
a[1:4, 4]

array([ 9, 14, 19])

In [87]:
a[0:2, 0:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [88]:
a[a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [89]:
(a % 2 == 0) & (a % 3 == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False]])

In [94]:
a.transpose()  # a.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [96]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [98]:
b[0] = 4
a  # Меняется!

array([[ 4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [109]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
c = np.resize(a, (2, 2))
c

array([[1, 2],
       [3, 4]])

In [112]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
a = np.linspace(1, 3, 5)
a

array([1. , 1.5, 2. , 2.5, 3. ])

In [118]:
a = np.insert(a, 4, 2)
a

array([1. , 1.5, 2. , 2.5, 2. , 3. ])

In [120]:
a = np.delete(a, 1)
a

array([1. , 2. , 2.5, 2. , 3. ])

**Клеим**

In [123]:
a = np.array([1, 2, 3, 4]).reshape((2, 2))
b = np.array([5, 6, 7, 8]).reshape((2, 2))
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [124]:
np.concatenate((a, b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [127]:
c = np.hstack((a, b))
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [128]:
d = np.vstack((a, b))
d

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [129]:
c[0, 0] = 100
a

array([[1, 2],
       [3, 4]])

In [132]:
e = np.concatenate((a, b, a+b), axis=1)
e

array([[ 1,  2,  5,  6,  6,  8],
       [ 3,  4,  7,  8, 10, 12]])

**Еще полезные функции**

In [136]:
x = [1, 2, 3, 4, 5]
y = [0, 5, 10, 15, 20, 25, 30]

XY = np.meshgrid(x, y)
XY

[array([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]),
 array([[ 0,  0,  0,  0,  0],
        [ 5,  5,  5,  5,  5],
        [10, 10, 10, 10, 10],
        [15, 15, 15, 15, 15],
        [20, 20, 20, 20, 20],
        [25, 25, 25, 25, 25],
        [30, 30, 30, 30, 30]])]

In [139]:
a.itemsize  # В байтах

4